micronaut.application.name=sysPersonaTerceraEdad

# ===== H2 BASE DE DATOS (archivo persistente) =====
datasources.default.url=jdbc:h2:file:./data/syspersona;DB_CLOSE_ON_EXIT=FALSE
datasources.default.driver-class-name=org.h2.Driver
datasources.default.username=sa
datasources.default.password=
datasources.default.schema-generate=CREATE
datasources.default.dialect=H2

datasources.default.maximum-pool-size=5
datasources.default.minimum-idle=1
